
// This file has been generated by the GUI designer. Do not modify.
namespace FileArchiveToolTest
{
	public partial class MainWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FileArchiveToolTest.MainWindow
			this.Name = "FileArchiveToolTest.MainWindow";
			this.Title = "MainWindow";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 733;
			this.DefaultHeight = 390;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
