# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\e\work\client-new-0212\client_maintrunk\tools\pythonscript\packeff\PackEff\src\pack\ui\TabWidget.ui'
#
# Created: Thu Mar 20 21:08:31 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(568, 375)
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.m_btnEffSart = QtGui.QPushButton(self.tab)
        self.m_btnEffSart.setGeometry(QtCore.QRect(20, 10, 75, 30))
        self.m_btnEffSart.setObjectName("m_btnEffSart")
        self.m_textEffLog = QtGui.QPlainTextEdit(self.tab)
        self.m_textEffLog.setGeometry(QtCore.QRect(10, 70, 541, 271))
        self.m_textEffLog.setPlainText("")
        self.m_textEffLog.setObjectName("m_textEffLog")
        self.m_btnEffCopy = QtGui.QPushButton(self.tab)
        self.m_btnEffCopy.setGeometry(QtCore.QRect(20, 40, 75, 30))
        self.m_btnEffCopy.setObjectName("m_btnEffCopy")
        self.m_rbtnCommon = QtGui.QRadioButton(self.tab)
        self.m_rbtnCommon.setGeometry(QtCore.QRect(240, 0, 89, 16))
        self.m_rbtnCommon.setObjectName("m_rbtnCommon")
        self.m_rbtnNCCenter = QtGui.QRadioButton(self.tab)
        self.m_rbtnNCCenter.setGeometry(QtCore.QRect(240, 20, 89, 16))
        self.m_rbtnNCCenter.setObjectName("m_rbtnNCCenter")
        self.m_rbtnCCenter = QtGui.QRadioButton(self.tab)
        self.m_rbtnCCenter.setGeometry(QtCore.QRect(240, 40, 131, 16))
        self.m_rbtnCCenter.setObjectName("m_rbtnCCenter")
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(360, 10, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(360, 30, 54, 12))
        self.label_2.setObjectName("label_2")
        self.m_plainTextEditWidth = QtGui.QPlainTextEdit(self.tab)
        self.m_plainTextEditWidth.setGeometry(QtCore.QRect(430, 0, 104, 21))
        self.m_plainTextEditWidth.setObjectName("m_plainTextEditWidth")
        self.m_plainTextEditHeight = QtGui.QPlainTextEdit(self.tab)
        self.m_plainTextEditHeight.setGeometry(QtCore.QRect(430, 30, 104, 21))
        self.m_plainTextEditHeight.setObjectName("m_plainTextEditHeight")
        self.m_btnEffBuildCfg = QtGui.QPushButton(self.tab)
        self.m_btnEffBuildCfg.setGeometry(QtCore.QRect(100, 10, 75, 31))
        self.m_btnEffBuildCfg.setObjectName("m_btnEffBuildCfg")
        self.m_btnEffCopyCfg = QtGui.QPushButton(self.tab)
        self.m_btnEffCopyCfg.setGeometry(QtCore.QRect(100, 40, 75, 31))
        self.m_btnEffCopyCfg.setObjectName("m_btnEffCopyCfg")
        TabWidget.addTab(self.tab, "")
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName("tab1")
        self.m_textCharLog = QtGui.QPlainTextEdit(self.tab1)
        self.m_textCharLog.setGeometry(QtCore.QRect(10, 70, 541, 271))
        self.m_textCharLog.setPlainText("")
        self.m_textCharLog.setObjectName("m_textCharLog")
        self.m_btnCharSart = QtGui.QPushButton(self.tab1)
        self.m_btnCharSart.setGeometry(QtCore.QRect(20, 10, 75, 30))
        self.m_btnCharSart.setObjectName("m_btnCharSart")
        self.m_btnCharCopy = QtGui.QPushButton(self.tab1)
        self.m_btnCharCopy.setGeometry(QtCore.QRect(20, 40, 75, 30))
        self.m_btnCharCopy.setObjectName("m_btnCharCopy")
        self.m_btnChaBuildCfg = QtGui.QPushButton(self.tab1)
        self.m_btnChaBuildCfg.setGeometry(QtCore.QRect(100, 10, 75, 31))
        self.m_btnChaBuildCfg.setObjectName("m_btnChaBuildCfg")
        self.m_btnChaCopyCfg_2 = QtGui.QPushButton(self.tab1)
        self.m_btnChaCopyCfg_2.setGeometry(QtCore.QRect(100, 40, 75, 31))
        self.m_btnChaCopyCfg_2.setObjectName("m_btnChaCopyCfg_2")
        TabWidget.addTab(self.tab1, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.m_textTerLog = QtGui.QPlainTextEdit(self.tab_2)
        self.m_textTerLog.setGeometry(QtCore.QRect(10, 70, 541, 271))
        self.m_textTerLog.setPlainText("")
        self.m_textTerLog.setObjectName("m_textTerLog")
        self.m_btnTerSart = QtGui.QPushButton(self.tab_2)
        self.m_btnTerSart.setGeometry(QtCore.QRect(20, 10, 75, 30))
        self.m_btnTerSart.setObjectName("m_btnTerSart")
        self.m_btnTerCopy = QtGui.QPushButton(self.tab_2)
        self.m_btnTerCopy.setGeometry(QtCore.QRect(20, 40, 75, 30))
        self.m_btnTerCopy.setObjectName("m_btnTerCopy")
        self.m_rbtnFightTer = QtGui.QRadioButton(self.tab_2)
        self.m_rbtnFightTer.setGeometry(QtCore.QRect(120, 10, 89, 16))
        self.m_rbtnFightTer.setAutoExclusive(False)
        self.m_rbtnFightTer.setObjectName("m_rbtnFightTer")
        self.m_rbtnJustXml = QtGui.QRadioButton(self.tab_2)
        self.m_rbtnJustXml.setGeometry(QtCore.QRect(120, 30, 141, 16))
        self.m_rbtnJustXml.setAutoExclusive(False)
        self.m_rbtnJustXml.setObjectName("m_rbtnJustXml")
        TabWidget.addTab(self.tab_2, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        TabWidget.setWindowTitle(QtGui.QApplication.translate("TabWidget", "TabWidget", None, QtGui.QApplication.UnicodeUTF8))
        self.m_btnEffSart.setText(QtGui.QApplication.translate("TabWidget", "start", None, QtGui.QApplication.UnicodeUTF8))
        self.m_btnEffCopy.setText(QtGui.QApplication.translate("TabWidget", "copy", None, QtGui.QApplication.UnicodeUTF8))
        self.m_rbtnCommon.setText(QtGui.QApplication.translate("TabWidget", "通用裁剪", None, QtGui.QApplication.UnicodeUTF8))
        self.m_rbtnNCCenter.setText(QtGui.QApplication.translate("TabWidget", "中心点不变", None, QtGui.QApplication.UnicodeUTF8))
        self.m_rbtnCCenter.setText(QtGui.QApplication.translate("TabWidget", "中心点不变指定大小", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("TabWidget", "宽度", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("TabWidget", "高度", None, QtGui.QApplication.UnicodeUTF8))
        self.m_btnEffBuildCfg.setText(QtGui.QApplication.translate("TabWidget", "build cfg", None, QtGui.QApplication.UnicodeUTF8))
        self.m_btnEffCopyCfg.setText(QtGui.QApplication.translate("TabWidget", "copy cfg", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), QtGui.QApplication.translate("TabWidget", "effect", None, QtGui.QApplication.UnicodeUTF8))
        self.m_btnCharSart.setText(QtGui.QApplication.translate("TabWidget", "start", None, QtGui.QApplication.UnicodeUTF8))
        self.m_btnCharCopy.setText(QtGui.QApplication.translate("TabWidget", "copy", None, QtGui.QApplication.UnicodeUTF8))
        self.m_btnChaBuildCfg.setText(QtGui.QApplication.translate("TabWidget", "build cfg", None, QtGui.QApplication.UnicodeUTF8))
        self.m_btnChaCopyCfg_2.setText(QtGui.QApplication.translate("TabWidget", "copy cfg", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget.setTabText(TabWidget.indexOf(self.tab1), QtGui.QApplication.translate("TabWidget", "character", None, QtGui.QApplication.UnicodeUTF8))
        self.m_btnTerSart.setText(QtGui.QApplication.translate("TabWidget", "start", None, QtGui.QApplication.UnicodeUTF8))
        self.m_btnTerCopy.setText(QtGui.QApplication.translate("TabWidget", "copy", None, QtGui.QApplication.UnicodeUTF8))
        self.m_rbtnFightTer.setText(QtGui.QApplication.translate("TabWidget", "战斗地形", None, QtGui.QApplication.UnicodeUTF8))
        self.m_rbtnJustXml.setText(QtGui.QApplication.translate("TabWidget", "仅仅导出xml配置文件", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("TabWidget", "terrain", None, QtGui.QApplication.UnicodeUTF8))

