filein "kok2_scripts/Kok2ExtendMaterial.ms"
filein "kok2_scripts/Kok2MeshOptions_ca.ms"

filein "kok2_scripts/fn_AddKok2MeshCustomAttribute.ms"
filein "kok2_scripts/macro_Kok2MeshCustomAttribute.ms"

filein "kok2_scripts/plugin_kok2expdata.ms"

filein "kok2_scripts/fn_ExportAndConvert.ms"
filein "kok2_scripts/macro_kok2exporter.ms"

filein "kok2_scripts/macro_kok2preview_noui.ms"

filein "kok2_scripts/fn_bindmenu.ms"
kok2_loadmenu()